animereviews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reviews.urls')),
    path('users/',include('users.urls')),
    path('api/',include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name='reset_password'),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"),name="password_reset_complete"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('animes/',views.getAnimes),
    path('anime/<str:id>/',views.getAnime),
    path('anime/<str:id>/rate/',views.rateAnime),

    path('reviews/',views.getReviews),
    path('review/<str:id>/',views.getReview),

    path('categories/',views.getCategories),
    path('category/<str:id>/',views.getCategory),
    
    path('profiles/',views.getProfiles),
    path('profile/<str:id>/',views.getProfile),


]

reviews/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('anime/<str:id>/', views.anime_detail, name='anime_detail'),

    path('delete-review/<str:id>/', views.deleteReview, name='delete_review'),

]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

from users.models import Profile
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name
    
class Anime(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(null=True,blank=True)
    image = models.ImageField(upload_to='anime_images/',blank=True,null=True)
    categories = models.ManyToManyField(Category)
    release_date = models.DateField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    @property
    def average_rating(self):
        reviews = self.reviews.all()
        if reviews.exists():
            return round(reviews.aggregate(Avg('rating'))['rating__avg'],2)
        return 0
    
    @property
    def review_count(self):
        return self.reviews.count()
    

    
class Review(models.Model):
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE, related_name="reviews")
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True,blank=True)
    rating = models.PositiveIntegerField(choices=[(i, str(i)) for i in range(1,6)])
    body_text = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return self.body_text[0:105]

reviews/forms.py
from django import forms
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating','body_text']

reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Anime, Review, Category
from .forms import ReviewForm
from .utils import get_user_profile,average_stars, paginateAnimes,searchAnime
from users.models import Profile


# Create your views here.
def home(request):
    animes, q = searchAnime(request)
    custom_range, animes = paginateAnimes(request,animes, 3)

    categories = Category.objects.all()
    anime_count = Anime.objects.all().count()
    
    profile = get_user_profile(request.user)
    
    context = {'categories':categories,'profile':profile,'animes':animes,'anime_count':anime_count,'q':q,'custom_range':custom_range}

    return render(request,'reviews/home.html', context)

def anime_detail(request, id):
    anime = get_object_or_404(Anime, id=id)
    full_stars, half_star, empty_stars = average_stars(anime.average_rating)
    percentage = (anime.average_rating / 5 ) * 100 if anime.average_rating > 0 else 0
    reviews = anime.reviews.all()
    review_user_ids = reviews.values_list('owner__id', flat=True)
    form = ReviewForm()
    
    profile = get_user_profile(request.user)
    is_favorite = profile.favorites.filter(id=anime.id).exists() if profile else False


    if request.method == 'POST':
        if 'submit_review' in request.POST:
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.anime = anime
                review.owner = profile
                review.save()
                return redirect('anime_detail', id=id)
            
        if 'favorite' in request.POST:
            if profile:
                if anime not in profile.favorites.all():
                    profile.favorites.add(anime)
                    return redirect('anime_detail', id=id)
                else:
                    profile.favorites.remove(anime)
                    return redirect('anime_detail', id=id)
            else:
                return redirect('login')
            
    context = {'anime':anime,'full_stars':range(full_stars),'half_star':half_star,'empty_stars':range(empty_stars),'percentage':round(percentage,2),'reviews':reviews,'form':form,'review_user_ids':review_user_ids,'is_favorite':is_favorite}
    return render(request,'reviews/anime_detail.html',context)

@login_required(login_url='login')
def deleteReview(request,id):
    review = get_object_or_404(Review, id=id)

    if request.method == 'POST':
        review.delete()
        return redirect('home')
    context = {'obj':review}
    return render(request,'reviews/delete_obj.html',context)

reviews/templates/reviews/anime_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="anime-details">
    <h1 class="anime-title">{{anime.title}}</h1>
    <div class="rating">
        Average Rating: 
        <span class="stars"> 

                {% for _ in full_stars %}
                    <i class="fas fa-star"></i>
                {% endfor %}
                {% if half_star %}
                    <i class="fas fa-star-half-alt"></i>
                {% endif %}
                {% for _ in empty_stars %}
                    <i class="far fa-star"></i>
                {% endfor %}
        </span>
        <p>Rating percentage: <strong>{{percentage}}</strong></p>
        <p>Total reviews: {{anime.review_count}}</p>
    </div>
    
    <p class="anime-description">{{anime.description}}</p>
    <img src="{{anime.image.url}}" alt="{{anime.title}}" class="anime-image">

    <form action="" method="POST" style="margin-bottom: 20px;">
        {% csrf_token %}
        {% if is_favorite %}
            <button type="submit" name="favorite" class="btn">Remove from Favorites</button>
        {% else %}
            <button type="submit" name="favorite" class="btn">Add to Favorites</button>
        {% endif %}
    </form>

    <div class="anime-categories">
        <h3>Categories:</h3>
        {% for category in anime.categories.all %}
            <span class="category"><a href="{% url 'home' %}?q={{category.name}}">{{category.name}}</a></span>
        {% endfor %}
    </div>
    <div class="anime-release-date">
        <p>First episode: {{anime.release_date}}</p>
    </div>
    <br>
    <div class="anime-reviews">
        <h2>Reviews:</h2>
        {% if anime.reviews %}
            {% for review in reviews %}
                <div class="review">
                    <p>
                        <img src="{{ review.owner.profile_img.url }}" alt="Profile Image" style="width: 40px; height: 40px; border-radius: 50%; object-fit: cover; vertical-align: middle; margin-right: 10px;">
                        <a href="{% url 'profile' review.owner.id %}" style="color: #333;text-decoration: none;">
                            {{ review.owner }}
                        </a>
                        - rated {{ review.rating }}
                    </p>
                    <span class="centered-text">{{ review.body_text }}</span>
                    {% if request.user.profile == review.owner %}
                    <a href="{% url 'delete_review' review.id %}" class="delete-link">Delete</a>
                    {% endif %}
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <p>No reviews yet for this anime</p>
        {% endif %}
    </div>
    
    <div class="submit-review">
        {% if request.user.profile.id in review_user_ids %}
            <p>You have already submitted your review for this anime</p>
        {% elif request.user.is_authenticated %}
            <form action="" method="POST" class="review-form">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="submit_review" value="Send review" class="btn">
                <input type="button" value="Cancel" onclick="history.back()" class="btn cancel-btn">
            </form>
        {% else %}
            <h3>You must log in to review this anime</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

reviews/templates/reviews/delete_obj.html
{% extends 'base.html' %}

{% block content %}
<div class="auth-container">
    <h2>Confirm Delete</h2>
    <form action="" method="POST" class="auth-form">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ obj }}"?</p>
        <button type="submit" class="btn">Confirm</button>
        <button type="button" class="btn cancel-btn" onclick="history.back()">Cancel</button>
    </form>
</div>
{% endblock %}

reviews/templates/reviews/home.html
{% extends 'base.html' %}

{% block content %}
<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 4fr;
    }
    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 20px;
        text-align: center;
    }
    .pagination ul {
        list-style-type: none;
        padding: 0;
        display: flex;
    }
    .pagination li {
        margin: 0 5px;
    }
    .pagination a {
        text-decoration: none;
        padding: 8px 16px;
        color: #000;
        border: 1px solid #ddd;
        border-radius: 4px;
    }
    .pagination a:hover {
        background-color: #ddd;
    }
</style>

<div class="home-container">
    <div class="categories-list">
        <h2>Categories:</h2>
        <div>
            <a href="{% url 'home' %}">All <span>{{anime_count}}</span></a>
        </div> 
        {% for category in categories %}
        <div>
            <a href="{% url 'home' %}?q={{category.name}}">{{category.name}} <span>{{category.anime_set.all.count}}</span></a>
        </div>
        {% endfor %}
    </div>

    <div class="anime-list">
        {% for anime in animes %}
            <div class="anime-item">
                {% if anime.image %}
                    <div class="anime-image-container">
                        <img src="{{anime.image.url}}" alt="{{anime.title}}" class="anime-image">
                    </div>
                {% endif %}
                <h2><a href="{% url 'anime_detail' anime.id %}" class="anime-title">{{anime.title}}</a></h2>
                {% for category in anime.categories.all %}
                    <span class="category">{{category}}</span>
                {% endfor %}
                <p class="anime-description">{{anime.description}}</p>
            </div>
        {% endfor %}
    </div>
</div>

{% if animes.has_other_pages %}
    <div class="pagination">
        <ul>

            {% if animes.has_previous %}
                <li><a href="?q={{q}}&page={{animes.previous_page_number}}" class="button">&#10094; Prev</a></li>
            {% endif %}

            {% for page in custom_range %}
                {% if page == animes.number %}
                <li><a href="?q={{q}}&page={{page}}" style="background-color: beige;">{{page}}</a></li>
                {% else %}
                <li><a href="?q={{q}}&page={{page}}" class="button">{{page}}</a></li>
                {% endif %}
            {% endfor %}

            {% if animes.has_next %}
                <li><a href="?q={{q}}&page={{animes.next_page_number}}" class="button">Next &#10095; </a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}

{% endblock %}

reviews/templates/reviews/test.html
{% extends 'base.html' %}

{% block content %}
<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 4fr;

    }
</style>

<div class="home-container">
    <div class="categories-list">
        <h2>Categories:</h2>
        {% for category in categories %}
            <p>{{ category.name }}</p>
        {% endfor %}
    </div>

    <div class="anime-list">
        {% for anime in animes %}
            <div class="anime-item">
                {% if anime.image %}
                    <img src="{{ anime.image.url }}" alt="{{ anime.title }}" class="anime-image">
                {% endif %}
                <h2><a href="{% url 'anime_detail' anime.id %}" class="anime-title">{{ anime.title }}</a></h2>
                <p class="anime-description">{{ anime.description }}</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}